yapb/yapb

project/yapb.vcxproj
source/manager.cpp

added /GL to msvc

---

project/yapb.vcxproj
source/manager.cpp
source/support.cpp

disables debug information for release builds

fixed cs16-client+xash3d on non-android platforms compatability

---

.gitignore
include/core.h
include/corelib.h
include/engine.h
source/basecode.cpp
source/combat.cpp
source/engine.cpp
source/interface.cpp
source/manager.cpp
source/navigate.cpp

Tweaked a little weapon recoil compensation code.
Some of the cosmetic code changes.
Rewrote chatter loading code, so it's works a bit faster now.
Optimized angle clamping in bot  vision code.

Removed support for original Xash CSDM mod.

---

source/manager.cpp

Fix yb_join_after_player_bug from issue by GoDhAnD-897

Fix yb_join_after_player_bug

---

cfg/addons/yapb/conf/lang/ru_lang.cfg
src/control.cpp

Updated translation for weapon modes:
Now, "Knife weapon mode selected" translated as "Выбран режим оружия: ножи" (previously "Knife режим оружия выбран") etc.
control.cpp changes:
Fixed typos in arguments for yb add, yb fill and yb g acquire_editor commands

Update Russian translation

---

cfg/addons/yapb/conf/lang/ru_lang.cfg
src/control.cpp

Translated new cvars and commands

Update Russian language

---

cfg/addons/yapb/conf/lang/de_chat.cfg
cfg/addons/yapb/conf/lang/de_lang.cfg

Updates and fixes the german translation for the latest version of YaPB.

update: german translation

---

cfg/addons/yapb/conf/lang/ru_lang.cfg

Обновление и исправление русского перевода для последней версии yapb

Update Russian translation for latest yapb version

---

src/botlib.cpp
src/chatlib.cpp
src/config.cpp
src/control.cpp
src/engine.cpp
src/manager.cpp

Some fixes for descriptions of console commands and variables

Fixes of typos, punctuations, mistranslation

---

cfg/addons/yapb/conf/lang/de_lang.cfg
cfg/addons/yapb/conf/lang/ru_lang.cfg

Updated English template for Deutsch language config
Translation fixes and additions for Russian translation

Some translation fixes and additions

---

src/control.cpp

Related to: https://github.com/yapb/yapb/issues/306

fix: display message about missing camp points

---

src/graph.cpp

for Terrorists and Counter-Terrorists respectively

add: red and blue arrows pointing to danger index

---

src/control.cpp

Previously, the bot count started from zero, i.e. 0 - 1, 1 - 2 etc.

fix: filling the server with bots one more than specified

---

src/manager.cpp

Related to: https://github.com/yapb/yapb/issues/415

add: yb_kick_after_player_connect cvar

---

cfg/addons/yapb/conf/lang/de_lang.cfg
cfg/addons/yapb/conf/lang/ru_lang.cfg
cfg/addons/yapb/conf/yapb.cfg
inc/yapb.h
src/botlib.cpp
src/combat.cpp
src/graph.cpp
src/manager.cpp

fix: some typos in cvar descriptions, etc.

cfg: ru_lang.cfg: translated new strings

---

cfg/addons/yapb/conf/lang/ru_lang.cfg
inc/graph.h
src/control.cpp
src/graph.cpp

Differences from commit by commandcobra7:
If there is already an outgoing or two-way (bidirectional) path from the source node to the destination node, the outgoing path will be removed and an outgoing jump path will be added.

add: creating a jump path via menu and console command

---

src/combat.cpp

Minor optimizations in conditions (changed sequence of OR checks, simplified flags check)

Fixed enemy selection when several shielded enemies are visible

---

src/analyze.cpp
src/control.cpp
src/manager.cpp

See discussion: https://github.com/yapb/yapb/discussions/470

fix: cvars bounds

---

inc/yapb.h
src/botlib.cpp
src/tasks.cpp
src/vision.cpp

aim: now looks at next node while navigating.
task: normal: bots walk if we hear enemies instead of suspecting.

aim: now looks at next node while navigating

---

cfg/addons/yapb/conf/yapb.cfg
inc/graph.h
inc/yapb.h
src/botlib.cpp
src/combat.cpp
src/graph.cpp
src/navigate.cpp
src/tasks.cpp
src/vision.cpp

task: normal: skip sniper node if no sniper weapon.
task: normal: don't walk if there are no enemies left and they are using knives.
task: attack: get proper function if bots lose close node after attack task.
nav: unnecessary codes cleared.
combat: attack movements reviewed.
bot: enemy hearing is now better. (thanks for the @spodlesniy idea)
desire: increased desire to seek cover by distance. (made for zombie plague mod)

fix: texts have been corrected.

---

src/graph.cpp

I changed the radius color, as pure blue mixes in with the white snow texture, and makes it barely visible

graph: slightly change the radius color

---

cfg/addons/yapb/conf/lang/de_lang.cfg
cfg/addons/yapb/conf/lang/ru_lang.cfg
src/control.cpp

Correct letter cases in other menu items + update Russian translation

menus: text corrections

---

README.md

readme: remove political thing

---

inc/manager.h
inc/yapb.h
src/botlib.cpp
src/combat.cpp
src/manager.cpp
src/navigate.cpp
src/support.cpp
src/tasks.cpp
src/vision.cpp

by the way i forgot to write. i added a new door entity. i also added a function for bots not to break the seventh material. they will no longer be able to break the tracking device in the terrorist base on the cs_1337_assault map.

nav: fall controls are not good.
